### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by thoraxmax** [CyberZHG/keras-adabound#3]
**Describe the Bug**

Hi, I wanted to try this interesting optimizer but I got this error using te example code.
Does the package don't support categorical_crossentropy?
Thanks!
**Version Info**

* [ ] I'm using the latest version
keras is version '2.3.1'

**Minimal Codes To Reproduce**

```python
from keras_adabound import AdaBound
autoencoder.compile(loss="categorical_crossentropy", optimizer=AdaBound(lr=0.001, final_lr=0.1), metrics=['categorical_accuracy'])
######error output###
  File "C:\chap\GazeTracking\synthetic\train_segNot3D.py", line 389, in <module>
    autoencoder.compile(loss="categorical_crossentropy", optimizer=AdaBound(lr=0.001, final_lr=0.1), metrics=['categorical_accuracy'])

  File "C:\ProgramData\Anaconda3\envs\crash\lib\site-packages\keras_adabound\optimizers.py", line 31, in __init__
    self.lr = K.variable(lr, name='lr')

AttributeError: can't set attribute
pass
```

**Comment by stromgald2** [comment]
try learning_rate instead of lr. i think for keras 2.3 is learning_rate

**Comment by zawa00moto** [comment]
I have the exact same issue on keras version 2.3.1.
I have tried "learning_rate", but it doesn't work as well.

**Comment by ZumelzuR** [comment]
This specific exception "AttributeError: can't set attribute" is [raised](https://github.com/python/cpython/blob/5ff7132313eb651107b179d20218dfe5d4e47f13/Objects/descrobject.c#L1415) when the attribute you're attempting to change is actually a property that doesn't have a setter. For fix this should be a setter defined for this "lr" property

**Comment by kkviks** [comment]
Still facing the same issue.

**Comment by Kosisochi** [comment]
Even when i used the default attribute for learning rate i still had the same issue. Im working with keras 2.4.3
