### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by kkviks** [CyberZHG/keras-adabound#4]
**Describe the Bug**
I am working on Google Colab

Error: 
AttributeError                            Traceback (most recent call last)
<ipython-input-74-5bc1bae4fc1c> in <module>()
      1 from keras_adabound import AdaBound
----> 2 model.compile(optimizer=AdaBound(lr=1e-3, final_lr=0.1), loss='binary_crossentropy')

/usr/local/lib/python3.6/dist-packages/keras_adabound/optimizers.py in __init__(self, lr, final_lr, base_lr, beta_1, beta_2, gamma, epsilon, decay, weight_decay, amsgrad, **kwargs)
     29         with K.name_scope(self.__class__.__name__):
     30             self.iterations = K.variable(0, dtype='int64', name='iterations')
---> 31             self.lr = K.variable(lr, name='lr')
     32             self.final_lr = K.variable(final_lr, name='final_lr')
     33             self.beta_1 = K.variable(beta_1, name='beta_1')

AttributeError: can't set attribute

**Version Info**

I'm using the latest version

**Minimal Codes To Reproduce**

```python

!pip install keras-adabound

from keras_adabound import AdaBound
model.compile(optimizer=AdaBound(lr=1e-3, final_lr=0.1), loss='binary_crossentropy')

pass
```

**Comment by CyberZHG** [comment]
I updated the optimizer with `tf.keras` so that the latest versions of Keras (2.4.3) and TensorFlow (2.2.0) can use it.
